<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Iceshrimp.MfmSharp.Examples\Iceshrimp.MfmSharp.Examples.csproj" />
      <ProjectReference Include="..\Iceshrimp.MfmSharp\Iceshrimp.MfmSharp.csproj" />
    </ItemGroup>

</Project>
