<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Configurations>Debug;Release;Fuzz</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Iceshrimp.MfmSharp.Examples\Iceshrimp.MfmSharp.Examples.csproj" />
      <ProjectReference Include="..\Iceshrimp.MfmSharp\Iceshrimp.MfmSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.JavaScript.NodeApi" Version="0.9.9" />
    </ItemGroup>

</Project>
