<Project Sdk="MSTest.Sdk/3.7.1">

    <PropertyGroup>
      <Configurations>Debug;Release;Fuzz</Configurations>
      <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Iceshrimp.Assertions" Version="1.0.0" />
        <PackageReference Include="Microsoft.JavaScript.NodeApi" Version="0.9.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Iceshrimp.MfmSharp.Examples\Iceshrimp.MfmSharp.Examples.csproj" />
      <ProjectReference Include="..\Iceshrimp.MfmSharp\Iceshrimp.MfmSharp.csproj" />
    </ItemGroup>

</Project>
