<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <Configurations>Debug;Release;Fuzz</Configurations>
      <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="Microsoft.JavaScript.NodeApi" Version="0.9.9" />
    </ItemGroup>

</Project>
