<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.2.1</Version>
        <IsPackable>true</IsPackable>
        <Configurations>Debug;Release;Fuzz</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(FUZZ)' == 'true' ">
        <DefineConstants>$(DefineConstants);FUZZ</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    </ItemGroup>

</Project>
