<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Configurations>Debug;Release;Fuzz</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.JavaScript.NodeApi" Version="0.9.9" />
        <PackageReference Include="SharpFuzz" Version="2.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Iceshrimp.MfmSharp\Iceshrimp.MfmSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="findings*\**" />
      <None Remove="inputs*\**" />
    </ItemGroup>

</Project>
